// export const images = {
//   USA: require('../../assets/countries/us.png'),
//   Germany: require('../../assets/countries/de.png'),
//   Russia: require('../../assets/countries/ru.png'),
//   Italy: require('../../assets/countries/it.png'),
//   China: require('../../assets/countries/cn.png'),
//   Spain: require('../../assets/countries/es.png'),
// };

export const images = {
  UAE: require('../../assets/countries/ae.png'),
  Angola: require('../../assets/countries/ao.png'),
  'Burkina Faso': require('../../assets/countries/bf.png'),
  Burundi: require('../../assets/countries/bi.png'),
  Benin: require('../../assets/countries/bj.png'),
  Botswana: require('../../assets/countries/bw.png'),
  'Democratic Republic Congo': require('../../assets/countries/cd.png'),
  'Central African Republic': require('../../assets/countries/cf.png'),
  Congo: require('../../assets/countries/cg.png'),
  "Côte d'Ivoire": require('../../assets/countries/ci.png'),
  Cameroon: require('../../assets/countries/cm.png'),
  'Cape Verde': require('../../assets/countries/cv.png'),
  Djibouti: require('../../assets/countries/dj.png'),
  Algeria: require('../../assets/countries/dz.png'),
  Egypt: require('../../assets/countries/eg.png'),
  'Western Sahara': require('../../assets/countries/eh.png'),
  Eritrea: require('../../assets/countries/er.png'),
  Ethiopia: require('../../assets/countries/et.png'),
  Gabon: require('../../assets/countries/ga.png'),
  Ghana: require('../../assets/countries/gh.png'),
  Gambia: require('../../assets/countries/gm.png'),
  Guinea: require('../../assets/countries/gn.png'),
  'Equatorial Guinea': require('../../assets/countries/gq.png'),
  'Guinea-Bissau': require('../../assets/countries/gw.png'),
  Kenya: require('../../assets/countries/ke.png'),
  Comoros: require('../../assets/countries/km.png'),
  Liberia: require('../../assets/countries/lr.png'),
  Lesotho: require('../../assets/countries/ls.png'),
  Libya: require('../../assets/countries/ly.png'),
  Morocco: require('../../assets/countries/ma.png'),
  Madagascar: require('../../assets/countries/mg.png'),
  Mali: require('../../assets/countries/ml.png'),
  Mauritania: require('../../assets/countries/mr.png'),
  Mauritius: require('../../assets/countries/mu.png'),
  Malawi: require('../../assets/countries/mw.png'),
  Mozambique: require('../../assets/countries/mz.png'),
  Namibia: require('../../assets/countries/na.png'),
  Niger: require('../../assets/countries/ne.png'),
  Nigeria: require('../../assets/countries/ng.png'),
  Réunion: require('../../assets/countries/re.png'),
  Rwanda: require('../../assets/countries/rw.png'),
  Seychelles: require('../../assets/countries/sc.png'),
  Sudan: require('../../assets/countries/sd.png'),
  'Saint Helena, Ascension and Tristan da Cunha': require('../../assets/countries/sh.png'),
  'Sierra Leone': require('../../assets/countries/sl.png'),
  Senegal: require('../../assets/countries/sn.png'),
  Somalia: require('../../assets/countries/so.png'),
  'South Sudan': require('../../assets/countries/ss.png'),
  'Sao Tome and Principe': require('../../assets/countries/st.png'),
  Swaziland: require('../../assets/countries/sz.png'),
  Chad: require('../../assets/countries/td.png'),
  Togo: require('../../assets/countries/tg.png'),
  Tunisia: require('../../assets/countries/tn.png'),
  Tanzania: require('../../assets/countries/tz.png'),
  Uganda: require('../../assets/countries/ug.png'),
  Mayotte: require('../../assets/countries/yt.png'),
  'South Africa': require('../../assets/countries/za.png'),
  Zambia: require('../../assets/countries/zm.png'),
  Zimbabwe: require('../../assets/countries/zw.png'),
  Afghanistan: require('../../assets/countries/af.png'),
  Armenia: require('../../assets/countries/am.png'),
  Antartica: require('../../assets/countries/aq.png'),
  Azerbaijan: require('../../assets/countries/az.png'),
  Bangladesh: require('../../assets/countries/bd.png'),
  Bahrain: require('../../assets/countries/bh.png'),
  'Brunei Darussalam': require('../../assets/countries/bn.png'),
  Bhutan: require('../../assets/countries/bt.png'),
  'Bouvet Island': require('../../assets/countries/bv.png'),
  'Cocos (Keeling) Islands': require('../../assets/countries/cc.png'),
  China: require('../../assets/countries/cn.png'),
  'Christmas Island': require('../../assets/countries/cx.png'),
  Georgia: require('../../assets/countries/ge.png'),
  'South Georgia and the South Sandwich Islands': require('../../assets/countries/gs.png'),
  'Hong Kong': require('../../assets/countries/hk.png'),
  'Heard Island and McDonald Islands': require('../../assets/countries/hm.png'),
  Indonesia: require('../../assets/countries/id.png'),
  Israel: require('../../assets/countries/il.png'),
  'British Indian Ocean Territory': require('../../assets/countries/io.png'),
  India: require('../../assets/countries/in.png'),
  Iraq: require('../../assets/countries/iq.png'),
  Iran: require('../../assets/countries/ir.png'),
  Jordan: require('../../assets/countries/jo.png'),
  Japan: require('../../assets/countries/jp.png'),
  Kyrgyzstan: require('../../assets/countries/kg.png'),
  Cambodia: require('../../assets/countries/kh.png'),
  'North Korea': require('../../assets/countries/kp.png'),
  'S. Korea': require('../../assets/countries/kr.png'),
  Kuwait: require('../../assets/countries/kw.png'),
  Kazakhstan: require('../../assets/countries/kz.png'),
  'Lao People Democratic Republic': require('../../assets/countries/la.png'),
  Lebanon: require('../../assets/countries/lb.png'),
  'Sri Lanka': require('../../assets/countries/lk.png'),
  Myanmar: require('../../assets/countries/mm.png'),
  Mongolia: require('../../assets/countries/mn.png'),
  Macao: require('../../assets/countries/mo.png'),
  Maldives: require('../../assets/countries/mv.png'),
  Malaysia: require('../../assets/countries/my.png'),
  'New Caledonia': require('../../assets/countries/nc.png'),
  Nepal: require('../../assets/countries/np.png'),
  Oman: require('../../assets/countries/om.png'),
  Philippines: require('../../assets/countries/ph.png'),
  Pakistan: require('../../assets/countries/pk.png'),
  Qatar: require('../../assets/countries/qa.png'),
  Russia: require('../../assets/countries/ru.png'),
  'Saudi Arabia': require('../../assets/countries/sa.png'),
  Singapore: require('../../assets/countries/sg.png'),
  Suriname: require('../../assets/countries/sr.png'),
  'Syrian Arab Republic': require('../../assets/countries/sy.png'),
  'French Southern Territories': require('../../assets/countries/tf.png'),
  Thailand: require('../../assets/countries/th.png'),
  Tajikistan: require('../../assets/countries/tj.png'),
  'Timor-Leste': require('../../assets/countries/tl.png'),
  Turkmenistan: require('../../assets/countries/tm.png'),
  Turkey: require('../../assets/countries/tr.png'),
  Taiwan: require('../../assets/countries/tw.png'),
  Uzbekistan: require('../../assets/countries/uz.png'),
  'Viet Nam': require('../../assets/countries/vn.png'),
  Yemen: require('../../assets/countries/ye.png'),
  Andorra: require('../../assets/countries/ad.png'),
  Albania: require('../../assets/countries/al.png'),
  Austria: require('../../assets/countries/at.png'),
  'Aland Islands': require('../../assets/countries/ax.png'),
  'Bosnia and Herzegovina': require('../../assets/countries/ba.png'),
  Belgium: require('../../assets/countries/be.png'),
  Bulgaria: require('../../assets/countries/bg.png'),
  Belarus: require('../../assets/countries/by.png'),
  Switzerland: require('../../assets/countries/ch.png'),
  Czechia: require('../../assets/countries/cz.png'),
  Germany: require('../../assets/countries/de.png'),
  Denmark: require('../../assets/countries/dk.png'),
  Estonia: require('../../assets/countries/ee.png'),
  Spain: require('../../assets/countries/es.png'),
  Finland: require('../../assets/countries/fi.png'),
  France: require('../../assets/countries/fr.png'),
  'Faroe Islands': require('../../assets/countries/fo.png'),
  UK: require('../../assets/countries/gb.png'),
  Guernsey: require('../../assets/countries/gg.png'),
  Gibraltar: require('../../assets/countries/gi.png'),
  Greece: require('../../assets/countries/gr.png'),
  Croatia: require('../../assets/countries/hr.png'),
  Hungary: require('../../assets/countries/hu.png'),
  Ireland: require('../../assets/countries/ie.png'),
  'Isle of Man': require('../../assets/countries/im.png'),
  Iceland: require('../../assets/countries/is.png'),
  Italy: require('../../assets/countries/it.png'),
  Liechtenstein: require('../../assets/countries/li.png'),
  Lithuania: require('../../assets/countries/lt.png'),
  Luxembourg: require('../../assets/countries/lu.png'),
  Latvia: require('../../assets/countries/lv.png'),
  Monaco: require('../../assets/countries/mc.png'),
  Moldova: require('../../assets/countries/md.png'),
  Montenegro: require('../../assets/countries/me.png'),
  'North Macedonia': require('../../assets/countries/mk.png'),
  Malta: require('../../assets/countries/mt.png'),
  Netherlands: require('../../assets/countries/nl.png'),
  Norway: require('../../assets/countries/no.png'),
  Poland: require('../../assets/countries/pl.png'),
  Portugal: require('../../assets/countries/pt.png'),
  Romania: require('../../assets/countries/ro.png'),
  Serbia: require('../../assets/countries/rs.png'),
  Sweden: require('../../assets/countries/se.png'),
  Slovenia: require('../../assets/countries/si.png'),
  'Svalbard and Jan Mayen': require('../../assets/countries/sj.png'),
  Slovakia: require('../../assets/countries/sk.png'),
  'San Marino': require('../../assets/countries/sm.png'),
  Ukraine: require('../../assets/countries/ua.png'),
  'Vatican City State': require('../../assets/countries/va.png'),
  'Antigua and Barbuda': require('../../assets/countries/ag.png'),
  Anguilla: require('../../assets/countries/ai.png'),
  Aruba: require('../../assets/countries/aw.png'),
  Barbados: require('../../assets/countries/bb.png'),
  'Saint Barthélemy': require('../../assets/countries/bl.png'),
  Bermuda: require('../../assets/countries/bm.png'),
  'Bonaire  Sint Eustatius and Saba': require('../../assets/countries/bq.png'),
  Bahamas: require('../../assets/countries/bs.png'),
  Belize: require('../../assets/countries/bz.png'),
  Canada: require('../../assets/countries/ca.png'),
  'Costa Rica': require('../../assets/countries/cr.png'),
  Cuba: require('../../assets/countries/cu.png'),
  Curaçao: require('../../assets/countries/cw.png'),
  Dominica: require('../../assets/countries/dm.png'),
  'Dominican Republic': require('../../assets/countries/do.png'),
  Grenada: require('../../assets/countries/gd.png'),
  Greenland: require('../../assets/countries/gl.png'),
  Guadeloupe: require('../../assets/countries/gp.png'),
  Guatemala: require('../../assets/countries/gt.png'),
  Honduras: require('../../assets/countries/hn.png'),
  Haiti: require('../../assets/countries/ht.png'),
  Jamaica: require('../../assets/countries/jm.png'),
  'Saint Kitts and Nevis': require('../../assets/countries/kn.png'),
  'Cayman Islands': require('../../assets/countries/ky.png'),
  'Saint Lucia': require('../../assets/countries/lc.png'),
  'Saint Martin (french)': require('../../assets/countries/mf.png'),
  Martinique: require('../../assets/countries/mq.png'),
  Montserrat: require('../../assets/countries/ms.png'),
  Mexico: require('../../assets/countries/mx.png'),
  Panama: require('../../assets/countries/pa.png'),
  'Saint Pierre and Miquelon': require('../../assets/countries/pm.png'),
  'Puerto Rico': require('../../assets/countries/pr.png'),
  'El Salvador': require('../../assets/countries/sv.png'),
  'Sint Maarten': require('../../assets/countries/sx.png'),
  'Turks and Caicos Islands': require('../../assets/countries/tc.png'),
  'Trinidad and Tobago': require('../../assets/countries/tt.png'),
  USA: require('../../assets/countries/us.png'),
  'Saint Vincent and the Grenadines': require('../../assets/countries/vc.png'),
  'Virgin Islands - British': require('../../assets/countries/vg.png'),
  'Virgin Islands US': require('../../assets/countries/vi.png'),
  'American Samoa': require('../../assets/countries/as.png'),
  Australia: require('../../assets/countries/au.png'),
  'Cook Islands': require('../../assets/countries/ck.png'),
  Fiji: require('../../assets/countries/fj.png'),
  Guam: require('../../assets/countries/gu.png'),
  Kiribati: require('../../assets/countries/ki.png'),
  'Norfolk Island': require('../../assets/countries/nf.png'),
  Nauru: require('../../assets/countries/nr.png'),
  Niue: require('../../assets/countries/nu.png'),
  'New Zealand': require('../../assets/countries/nz.png'),
  'French Polynesia': require('../../assets/countries/pf.png'),
  'Papua New Guinea': require('../../assets/countries/pg.png'),
  Pitcairn: require('../../assets/countries/pn.png'),
  Palau: require('../../assets/countries/pw.png'),
  'Solomon Islands': require('../../assets/countries/sb.png'),
  Tokelau: require('../../assets/countries/tk.png'),
  Tonga: require('../../assets/countries/to.png'),
  Vanuatu: require('../../assets/countries/vu.png'),
  'Wallis and Futuna': require('../../assets/countries/wf.png'),
  Samoa: require('../../assets/countries/ws.png'),
  Argentina: require('../../assets/countries/ar.png'),
  Bolivia: require('../../assets/countries/bo.png'),
  Brazil: require('../../assets/countries/br.png'),
  Chile: require('../../assets/countries/cl.png'),
  Colombia: require('../../assets/countries/co.png'),
  Ecuador: require('../../assets/countries/ec.png'),
  'Falkland Islands': require('../../assets/countries/fk.png'),
  'French Guiana': require('../../assets/countries/gf.png'),
  Guyana: require('../../assets/countries/gy.png'),
  Nicaragua: require('../../assets/countries/ni.png'),
  Peru: require('../../assets/countries/pe.png'),
  Paraguay: require('../../assets/countries/py.png'),
  Uruguay: require('../../assets/countries/uy.png'),
  Venezuela: require('../../assets/countries/ve.png'),
};
